name: nutricare_elderly
description: Mobile Dietary Recommendation System for Elderly Users (60+)

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.13.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  riverpod: 2.5.1
  flutter_riverpod: 2.5.1

  # Backend
  supabase_flutter: 1.10.25

  # Local Storage
  hive: 2.2.3
  hive_flutter: 1.1.0
  encrypted_shared_preferences: 2.1.0
  google_fonts: ^8.1.0

  # Utilities
  uuid: 4.0.0
  equatable: ^2.0.7
  intl: 0.19.0

  # HTTP & Serialization
  http: 1.1.0
  json_annotation: 4.9.0

  # Logging
  logger: 2.0.0
  url_launcher: ^6.3.0
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.4
  flutter_timezone: ^5.0.2
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  image_picker: ^1.2.2
  google_mlkit_text_recognition: ^0.15.1
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 3.0.2
  build_runner: 2.4.13
  hive_generator: 2.0.1
  json_serializable: 6.8.0
  widgetbook: 3.22.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo.png"

flutter_native_splash:
  color: "#F6F8F6"
  image: assets/images/logo.png
  android_12:
    image: assets/images/logo.png
    color: "#F6F8F6"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
